CFLAGS  = -g -Wall -fno-strict-aliasing
LDFLAGS =
INCLUDE = -I../../ 
DEFINE  =
LIB     = 


all:
	$(CC) $(CFLAGS)  -o testbit testbit.c $(LIB) $(INCLUDE) $(LDFLAGS) $(DEFINE)
	$(CC) $(CFLAGS)  -o testlist testlist.c $(LIB) $(INCLUDE) $(LDFLAGS) $(DEFINE)
	$(CC) $(CFLAGS)  -o testdlist testdlist.c $(LIB) $(INCLUDE) $(LDFLAGS) $(DEFINE)		